### ISSUE TITLE
S3

### ISSUE THREAD

**Issue by hcarty** [inhabitedtype/ocaml-aws#15]
Are there any plans to support working with S3 directly?  Or does that exist already in the library/libraries somewhere?

**Comment by seliopou** [comment]
S3 will be included in the library shortly. The code generator needs to handle another data type, after which S3 code generation should be possible. That work is ongoing but hasn't been pushed to a public repository yet.

**Comment by hcarty** [comment]
Thanks for the update!

**Comment by toots** [comment]
Any progress on this? I'm down to helping is there's some code I can check out somewhere..
