### ISSUE TITLE
Not sure how to install and use the library

### ISSUE THREAD

**Issue by michipili** [inhabitedtype/ocaml-aws#17]
I tried to install the library using **opam** which somehow succeed but leaves me with only two modules `Aws` and `Aws_lwt`.  How can I arrange so that material found in `libraries/` is also compiled and installed?

Also, I am a bit confused by the whole `library/` directory. If I understand correctly, its content is generated by the `aws_gen` program. But why add this to the SCM system?

Thanks!

**Comment by seliopou** [comment]
There was a problem with the autogenerated OASIS files in the last release, which was fixed by #13. I need to cut a release to get this into OPAM, but until then you should be able to make progress by pinning to a local checkout.

**Comment by michipili** [comment]
Ah okay, thanks to your indications, I was able to actually generate the bindings, and to compile them with `cd libraries && make build` but I am still unsure what is the preferred way to install each individual library. Did you build opam support for this already? If not I could give a hand there.

**Comment by aymanosman** [comment]
+1 I'm an OCaml newb. Not understanding how to install and use this package.

**Comment by michipili** [comment]
Perfect, thanks!
