### ISSUE TITLE
Compilation fails for Ocaml 4.03.0

### ISSUE THREAD

**Issue by kstarikov** [inhabitedtype/ocaml-aws#18]
``` zsh
➜  ocaml-aws git:(master) make gen                                       
ocaml setup.ml -all 
File "./setup.ml", line 318, characters 20-36:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 318, characters 42-58:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 327, characters 14-30:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 327, characters 38-54:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 330, characters 25-41:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 368, characters 10-26:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 474, characters 13-29:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
File "./setup.ml", line 1825, characters 16-33:
Warning 3: deprecated: String.capitalize
Use String.capitalize_ascii instead.
File "./setup.ml", line 1831, characters 16-35:
Warning 3: deprecated: String.uncapitalize
Use String.uncapitalize_ascii instead.
File "setup.ml", line 5847, characters 11-28:
Warning 3: deprecated: String.capitalize
Use String.capitalize_ascii instead.
File "setup.ml", line 5848, characters 11-30:
Warning 3: deprecated: String.uncapitalize
Use String.uncapitalize_ascii instead.

Configuration: 
ocamlfind: ........................................... /home/kstarikov/.opam/4.03.0/bin/ocamlfind
ocamlc: .............................................. /home/kstarikov/.opam/4.03.0/bin/ocamlc.opt
ocamlopt: ............................................ /home/kstarikov/.opam/4.03.0/bin/ocamlopt.opt
ocamlbuild: .......................................... /home/kstarikov/.opam/4.03.0/bin/ocamlbuild
Package name: ........................................ aws
Package version: ..................................... 1.0.2
os_type: ............................................. Unix
system: .............................................. linux
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.03.0
standard_library_default: ............................ /home/kstarikov/.opam/4.03.0/lib/ocaml
standard_library: .................................... /home/kstarikov/.opam/4.03.0/lib/ocaml
standard_runtime: .................................... /home/kstarikov/.opam/4.03.0/bin/ocamlrun
bytecomp_c_compiler: ................................. gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT -fPIC
native_c_compiler: ................................... gcc -std=gnu99 -O2 -fno-strict-aliasing -fwrapv -Wall -D_FILE_OFFSET_BITS=64 -D_REENTRANT
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr/local
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... $exec_prefix/lib
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. $datarootdir/doc/$pkg_name
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
findlib_version: ..................................... 1.6.2
is_native: ........................................... true
suffix_program: ...................................... 
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ true
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: ......................... 
Build the Lwt runtime: ............................... false
Build the Async runtime: ............................. false
Build the code generation tool: ...................... true
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_ezxmlm: .......................................... /home/kstarikov/.opam/4.03.0/lib/ezxmlm
pkg_nocrypto: ........................................ /home/kstarikov/.opam/4.03.0/lib/nocrypto
pkg_calendar: ........................................ /home/kstarikov/.opam/4.03.0/lib/calendar
pkg_uri: ............................................. /home/kstarikov/.opam/4.03.0/lib/uri
ocamldoc: ............................................ /home/kstarikov/.opam/4.03.0/bin/ocamldoc
pkg_cmdliner: ........................................ /home/kstarikov/.opam/4.03.0/lib/cmdliner
pkg_yojson: .......................................... /home/kstarikov/.opam/4.03.0/lib/yojson
pkg_ppx_tools: ....................................... /home/kstarikov/.opam/4.03.0/lib/ppx_tools
pkg_ppx_tools_metaquot: .............................. /home/kstarikov/.opam/4.03.0/lib/ppx_tools
pkg_ocamlgraph: ...................................... /home/kstarikov/.opam/4.03.0/lib/ocamlgraph
pkg_unix: ............................................ /home/kstarikov/.opam/4.03.0/lib/ocaml

Finished, 0 targets (0 cached) in 00:00:00.
+ /home/kstarikov/.opam/4.03.0/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/syntax.cmo src/syntax.ml
File "src/syntax.ml", line 61, characters 13-112:
Error: This variant expression is expected to have type Asttypes.rec_flag
       The constructor :: does not belong to type Asttypes.rec_flag
Command exited with code 2.
Compilation unsuccessful after building 23 targets (21 cached) in 00:00:00.
E: Failure("Command ''/home/kstarikov/.opam/4.03.0/bin/ocamlbuild' lib/aws.cma lib/aws.cmxa lib/aws.a lib/aws.cmxs src/aws_gen.native -use-ocamlfind -tag debug' terminated with error code 10")
make: *** [all] Error 1
```

**Comment by avsm** [comment]
This is no longer an issue for me; with the latest ppx tools ocaml-aws compiles fine.  I've submitted #19 with an autogen update to suppress some warnings.

**Comment by kstarikov** [comment]
@avsm which version of `ppx_tools` do you use? I see the same error trying to `make gen` on your `aws-oasis` branch with ppx_tools `5.0+4.03.0`.

**Comment by ebsbk** [comment]
Got the same issue

`➜  ocaml-aws git:(master) ✗ make clean
ocaml setup.ml -clean
Finished, 0 targets (0 cached) in 00:00:00.
00:00:00 0    (0   ) STARTING                                                                                                                                                         -------- |%➜  ocaml-aws git:(master) ✗ ./configure --enable-gen

Configuration:
ocamlfind: ........................................... /Users/guest1/.opam/system/bin/ocamlfind
ocamlc: .............................................. /usr/local/bin/ocamlc.opt
ocamlopt: ............................................ /usr/local/bin/ocamlopt.opt
ocamlbuild: .......................................... /Users/guest1/.opam/system/bin/ocamlbuild
Package name: ........................................ aws
Package version: ..................................... 1.0.2
os_type: ............................................. Unix
system: .............................................. macosx
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.05.0
standard_library_default: ............................ /usr/local/lib/ocaml
standard_library: .................................... /usr/local/lib/ocaml
standard_runtime: .................................... /usr/local/bin/ocamlrun
bytecomp_c_compiler: ................................. gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT
native_c_compiler: ................................... gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr/local
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... $exec_prefix/lib
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. $datarootdir/doc/$pkg_name
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
findlib_version: ..................................... 1.7.3
is_native: ........................................... true
suffix_program: ......................................
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ true
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: .........................
Build the Lwt runtime: ............................... true
Build the Async runtime: ............................. false
Build the code generation tool: ...................... true
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_ezxmlm: .......................................... /Users/guest1/.opam/system/lib/ezxmlm
pkg_nocrypto: ........................................ /Users/guest1/.opam/system/lib/nocrypto
pkg_calendar: ........................................ /Users/guest1/.opam/system/lib/calendar
pkg_uri: ............................................. /Users/guest1/.opam/system/lib/uri
ocamldoc: ............................................ /usr/local/bin/ocamldoc
pkg_cohttp_lwt: ...................................... /Users/guest1/.opam/system/lib/cohttp
pkg_lwt: ............................................. /Users/guest1/.opam/system/lib/lwt
pkg_ssl: ............................................. /Users/guest1/.opam/system/lib/ssl
pkg_cmdliner: ........................................ /Users/guest1/.opam/system/lib/cmdliner
pkg_yojson: .......................................... /Users/guest1/.opam/system/lib/yojson
pkg_ppx_tools: ....................................... /Users/guest1/.opam/system/lib/ppx_tools
pkg_ppx_tools_metaquot: .............................. /Users/guest1/.opam/system/lib/ppx_tools
pkg_ocamlgraph: ...................................... /Users/guest1/.opam/system/lib/ocamlgraph
pkg_unix: ............................................ /usr/local/lib/ocaml

➜  ocaml-aws git:(master) ✗ make gen
ocaml setup.ml -all

Configuration:
ocamlfind: ........................................... /Users/guest1/.opam/system/bin/ocamlfind
ocamlc: .............................................. /usr/local/bin/ocamlc.opt
ocamlopt: ............................................ /usr/local/bin/ocamlopt.opt
ocamlbuild: .......................................... /Users/guest1/.opam/system/bin/ocamlbuild
Package name: ........................................ aws
Package version: ..................................... 1.0.2
os_type: ............................................. Unix
system: .............................................. macosx
architecture: ........................................ amd64
ccomp_type: .......................................... cc
ocaml_version: ....................................... 4.05.0
standard_library_default: ............................ /usr/local/lib/ocaml
standard_library: .................................... /usr/local/lib/ocaml
standard_runtime: .................................... /usr/local/bin/ocamlrun
bytecomp_c_compiler: ................................. gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT
native_c_compiler: ................................... gcc  -O2 -fno-strict-aliasing -fwrapv -D_FILE_OFFSET_BITS=64 -D_REENTRANT
model: ............................................... default
ext_obj: ............................................. .o
ext_asm: ............................................. .s
ext_lib: ............................................. .a
ext_dll: ............................................. .so
default_executable_name: ............................. a.out
systhread_supported: ................................. true
Install architecture-independent files dir: .......... /usr/local
Install architecture-dependent files in dir: ......... $prefix
User executables: .................................... $exec_prefix/bin
System admin executables: ............................ $exec_prefix/sbin
Program executables: ................................. $exec_prefix/libexec
Read-only single-machine data: ....................... $prefix/etc
Modifiable architecture-independent data: ............ $prefix/com
Modifiable single-machine data: ...................... $prefix/var
Object code libraries: ............................... $exec_prefix/lib
Read-only arch-independent data root: ................ $prefix/share
Read-only architecture-independent data: ............. $datarootdir
Info documentation: .................................. $datarootdir/info
Locale-dependent data: ............................... $datarootdir/locale
Man documentation: ................................... $datarootdir/man
Documentation root: .................................. $datarootdir/doc/$pkg_name
HTML documentation: .................................. $docdir
DVI documentation: ................................... $docdir
PDF documentation: ................................... $docdir
PS documentation: .................................... $docdir
findlib_version: ..................................... 1.7.3
is_native: ........................................... true
suffix_program: ......................................
Remove a file.: ...................................... rm -f
Remove a directory.: ................................. rm -rf
Turn ocaml debug flag on: ............................ true
Turn ocaml profile flag on: .......................... false
Compiler support generation of .cmxs.: ............... true
OCamlbuild additional flags: .........................
Build the Lwt runtime: ............................... true
Build the Async runtime: ............................. false
Build the code generation tool: ...................... true
Create documentations: ............................... true
Compile tests executable and library and run them: ... false
pkg_ezxmlm: .......................................... /Users/guest1/.opam/system/lib/ezxmlm
pkg_nocrypto: ........................................ /Users/guest1/.opam/system/lib/nocrypto
pkg_calendar: ........................................ /Users/guest1/.opam/system/lib/calendar
pkg_uri: ............................................. /Users/guest1/.opam/system/lib/uri
ocamldoc: ............................................ /usr/local/bin/ocamldoc
pkg_cohttp_lwt: ...................................... /Users/guest1/.opam/system/lib/cohttp
pkg_lwt: ............................................. /Users/guest1/.opam/system/lib/lwt
pkg_ssl: ............................................. /Users/guest1/.opam/system/lib/ssl
pkg_cmdliner: ........................................ /Users/guest1/.opam/system/lib/cmdliner
pkg_yojson: .......................................... /Users/guest1/.opam/system/lib/yojson
pkg_ppx_tools: ....................................... /Users/guest1/.opam/system/lib/ppx_tools
pkg_ppx_tools_metaquot: .............................. /Users/guest1/.opam/system/lib/ppx_tools
pkg_ocamlgraph: ...................................... /Users/guest1/.opam/system/lib/ocamlgraph
pkg_unix: ............................................ /usr/local/lib/ocaml

W: Cannot find source file matching module 'aws_lwt' in library aws_lwt.
W: Use InterfacePatterns or ImplementationPatterns to define this file with feature "source_patterns".
Finished, 1 target (0 cached) in 00:00:01.
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package uri -package nocrypto -package ezxmlm -package calendar -I lib -o lib/aws.cmo lib/aws.ml
File "lib/aws.ml", line 315, characters 20-36:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlopt -c -g -annot -bin-annot -package uri -package nocrypto -package ezxmlm -package calendar -I lib -o lib/aws.cmx lib/aws.ml
File "lib/aws.ml", line 315, characters 20-36:
Warning 3: deprecated: String.lowercase
Use String.lowercase_ascii instead.
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/structures.cmi src/structures.mli
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/util.cmi src/util.mli
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/generate.cmi src/generate.mli
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/reading.cmi src/reading.mli
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/templates.cmi src/templates.mli
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/aws_gen.cmo src/aws_gen.ml
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
File "src/aws_gen.ml", line 43, characters 31-45:
Warning 3: deprecated: Char.lowercase
Use Char.lowercase_ascii instead.
+ /Users/guest1/.opam/system/bin/ocamlfind ocamlc -c -g -annot -bin-annot -package yojson -package unix -package ppx_tools.metaquot -package ppx_tools -package ocamlgraph -package cmdliner -I src -o src/syntax.cmo src/syntax.ml
findlib: [WARNING] Interface topdirs.cmi occurs in several directories: /usr/local/lib/ocaml/compiler-libs, /usr/local/lib/ocaml
File "src/syntax.ml", line 61, characters 13-112:
Error: This variant expression is expected to have type Asttypes.rec_flag
       The constructor :: does not belong to type Asttypes.rec_flag
Command exited with code 2.
Compilation unsuccessful after building 33 targets (0 cached) in 00:00:02.
E: Failure("Command ''/Users/guest1/.opam/system/bin/ocamlbuild' lib/aws.cma lib/aws.cmxa lib/aws.a lib/aws.cmxs lwt/aws_lwt.cma lwt/aws_lwt.cmxa lwt/aws_lwt.a lwt/aws_lwt.cmxs src/aws_gen.native -use-ocamlfind -tag debug' terminated with error code 10")
make: *** [all] Error 1`
