### ISSUE TITLE
More SDK bindings?

### ISSUE THREAD

**Issue by anmonteiro** [inhabitedtype/ocaml-aws#30]
It looks to me that this library only supports a couple AWS services.

1. Am I wrong and things like S3 are supported already?

2. Are there plans to add more services as the library grows?

3. Unrelated question: can I install from opam with the lwt runtime support?

**Comment by seliopou** [comment]
You are correct that services like S3 are not currently supported, among other. I believe that @tmcgilchrist has an interest in expanding the number of supported services, and may be working on them in his free time.

You should be able to install from OPAM with lwt support. The current release should recognize the depopt and make `aws.lwt` available to you. Any issues with the current release, however, will remain until to switch to jbuilder. It's just not worth sinking more time into the Oasis build and release process. :/

Does that answer your questions?

**Comment by anmonteiro** [comment]
Thanks, definitely answers my questions.

I'm also interested in expanding the number of services supported. I've started looking at what's needed to make that happen.

**Comment by tmcgilchrist** [comment]
as @seliopou mentioned I'm working on porting to jbuilder. After that I personally need support for SQS, RDS and CloudWatch, so I'll be looking at supporting those first.

**Comment by anmonteiro** [comment]
@tmcgilchrist I've started some work that I wrote about in #31. I'm planning to continue on working on it so let me know how we sync up our efforts.
