### ISSUE TITLE
Supporting the entire AWS API

### ISSUE THREAD

**Issue by anmonteiro** [inhabitedtype/ocaml-aws#31]
I'm opening this issue to gather early feedback on some work I've been doing. 

I've started working on generating code to support all the AWS services on this branch: https://github.com/inhabitedtype/ocaml-aws/compare/master...anmonteiro:more-apis?expand=1

Let me know if this is something you'd be welcome to accept.

**Comment by tmcgilchrist** [comment]
Just having a quick glance I would be happy for the help in supporting more services.

A few points worth making:
1. Keep whitespace / formatting only changes to a minimum. My rule is to try and keep to whatever is already in the code unless they use tabs 😞 
2. Oasis based build it obviously going away.
3. Version ranges for packages would be nice. I'll defer to @seliopou on this but that's what I'm used to with Haskell packages.

**Comment by seliopou** [comment]
All sounds good. The smaller the chunks you can turn into PRs to facilitate review the better. I don't think I saw any generated code in there. My practice was do have a commit with code generation changes and then a follow-up commit with the changes to the generated code.

Whitespace changes only when touching code for sure. Helps keep the peace, so thanks for being sensitive to that.

With respect to version constraints: definitely in OPAM files. I used to selectively do it in `_oasis` files but that's going away so meh. Is that a thing in `jbuild` files?

**Comment by seliopou** [comment]
For each service that y'all are planning on working on, it'd be good to open an issue for each of them so everybody know's what's going on. I created a Milestone for full AWS coverage [here](https://github.com/inhabitedtype/ocaml-aws/milestone/2) that we can add the issues to.

**Comment by anmonteiro** [comment]
Not sure how easy it will be to break down my changes into multiple pull requests, but at the least I'll keep individual commits with self-contained changes.

**Comment by seliopou** [comment]
I think that generally speaking, separate services should be separate PRs. Any changes to code generation that don't actually affect existing output could probably be their own as well. As long as it's clear how the change in the code led to a change in the output, we should be good. :+1:

**Comment by anmonteiro** [comment]
@seliopou sorry, I wasn't clear.

So far the changes I made are not specific to any service, but meant to be generic to all of them.

I haven't committed the generated code because that would be distracting when reviewing the code generation code, and I will make sure to do those in separate PRs.

I'll open a PR with what I currently have to get some early feedback.

**Comment by anmonteiro** [comment]
Opened in https://github.com/inhabitedtype/ocaml-aws/pull/33

**Comment by tmcgilchrist** [comment]
@anmonteiro I'd welcome any specific PRs for new services. 
Thanks
